#Fri Nov 25 13:55:58 GMT 2022
micronaut:
  application:
    name: trading
r2dbc:
  datasources:
    default:
      username: postgres
      dialect: POSTGRES
      url: r2dbc:postgresql://postgres:5432/postgres
      password: postgres
      schema-generate: CREATE_DROP
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`http://redpanda:29092`}
netty:
  default:
    allocator:
      max-order: 3
redis:
  uri: redis://redis:6379
  caches:
    prices:
      charset: 'UTF-8'
      expire-after-write: 5m
      key-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
      value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer