micronaut:
  application:
    name: tradingMock
  server:
    port: 8090
netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`http://redpanda:29092`}
