micronaut:
  application:
    name: tradingMock
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9092`}
