apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscommander
  labels:
    app: rediscommander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rediscommander
  template:
    metadata:
      labels:
        app: rediscommander
    spec:
      containers:
        - name: rediscommander
          image: rediscommander/redis-commander:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOSTS
              value: 'local:redis:6379'
---
apiVersion: v1
kind: Service
metadata:
  name: rediscommander
spec:
  selector:
    app: rediscommander
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8081