apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/vectorized/redpanda:latest
          args:
            - redpanda
            - start
            - --smp 1
            - --overprovisioned
            - --node-id 0
            - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
            - --pandaproxy-addr 0.0.0.0:8082
            - --advertise-pandaproxy-addr redpanda:8082
            - --verbose
          ports:
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 9092
            - containerPort: 9644
            - containerPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: panda-8081
      protocol: TCP
      port: 8081
    - name: panda-8082
      protocol: TCP
      port: 8082
    - name: panda-9092
      protocol: TCP
      port: 9092
    - name: panda-29092
      protocol: TCP
      port: 29092
    - name: panda-9644
      protocol: TCP
      port: 9644